# Generated by Django 5.0 on 2024-01-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveAdmin',
        ),
    ]
