# Generated by Django 5.0 on 2024-01-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(choices=[('اعیاد رسمی', 'اعیاد رسمی'), ('معمولی', 'معمولی'), ('اضطراری', 'اضطراری')], max_length=100),
        ),
    ]
