# Generated by Django 5.0 on 2024-01-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_leave_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
