# Generated by Django 5.0 on 2024-01-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_alter_leave_end_date_alter_leave_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
    ]
