# Generated by Django 5.0 on 2023-12-26 06:27

import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_person_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAdmin',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_news_admin', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('user.person',),
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
