# Generated by Django 5.0 on 2023-12-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('INSTRUMENT', 'INSTRUMENT'), ('MAINTENANCE', 'MAINTENANCE'), ('MECHANICAL', 'MECHANICAL'), ('ELECTRICITY', 'ELECTRICITY'), ('IT', 'IT'), ('MANAGEMENT', 'MANAGEMENT')], max_length=50)),
            ],
        ),
    ]
