# Generated by Django 5.0 on 2023-12-31 13:48

import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_delete_employee'),
        ('user', '0003_person_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('department', models.CharField(choices=[('INSTRUMENT', 'INSTRUMENT'), ('MAINTENANCE', 'MAINTENANCE'), ('MECHANICAL', 'MECHANICAL'), ('ELECTRICITY', 'ELECTRICITY'), ('IT', 'IT'), ('MANAGEMENT', 'MANAGEMENT')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('user.person',),
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
