# Generated by Django 5.0 on 2024-01-19 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_initial'),
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Farvardin', 'Farvardin'), ('Ordibehesht', 'Ordibehesht'), ('Khordad', 'Khordad'), ('Tir', 'Tir'), ('Mordad', 'Mordad'), ('Shahrivar', 'Shahrivar'), ('Mehr', 'Mehr'), ('Aban', 'Aban'), ('Azar', 'Azar'), ('Dey', 'Dey'), ('Bahman', 'Bahman'), ('Esfand', 'Esfand')], max_length=20)),
                ('year', models.IntegerField()),
                ('salary_value', models.BigIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
