# Generated by Django 5.0 on 2024-01-26 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_is_employee'),
        ('trip', '0002_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='time',
        ),
        migrations.AddField(
            model_name='trip',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='trip',
            name='seat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
