# Generated by Django 5.0 on 2024-01-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_remove_trip_date_remove_trip_time_trip_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
