# Generated by Django 5.0 on 2023-12-24 17:25

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
